# Generated by Django 5.1.1 on 2025-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
